name: edu_play
description: "Soulstice - A Productivity App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  firebase_core: ^3.3.0
  provider: ^6.1.2
  dio: ^5.5.0+1
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # Offline Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.2.3

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
